export const products = [
  {
    id: 1,
    name: "T-shirt",
    description: "",
    price: 29.99,
    quantity: 10,
    amount: 0,
    favorite: false,
  },
  {
    id: 2,
    name: "Hoodie",
    description: "",
    price: 40.0,
    quantity: 6,
    amount: 0,
    favorite: false,
  },
  {
    id: 3,
    name: "Jacket",
    description: "",
    price: 60.0,
    quantity: 5,
    amount: 0,
    favorite: false,
  },
  {
    id: 4,
    name: "Jeans",
    description: "",
    price: 35.0,
    quantity: 12,
    amount: 0,
    favorite: false,
  },
  {
    id: 5,
    name: "Short",
    description: "",
    price: 19.99,
    quantity: 8,
    amount: 0,
    favorite: false,
  },
  {
    id: 6,
    name: "Glasses",
    description: "",
    price: 80.99,
    quantity: 3,
    amount: 0,
    favorite: false,
  },
  {
    id: 7,
    name: "Belt",
    description: "",
    price: 100.0,
    quantity: 6,
    amount: 0,
    favorite: false,
  },
  {
    id: 8,
    name: "Cap",
    description: "",
    price: 15.0,
    quantity: 6,
    amount: 0,
    favorite: false,
  },
  {
    id: 9,
    name: "Watch",
    description: "",
    price: 200.0,
    quantity: 3,
    amount: 0,
    favorite: false,
  },
  {
    id: 10,
    name: "Shoes",
    description: "",
    price: 99.99,
    quantity: 9,
    amount: 0,
    favorite: false,
  },
];
