// TYPES TO CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
// TYPES TO USER
export const ADD_USER = 'ADD_USER';
// TYPES TO FAVORITE PRODUCTS
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE ='REMOVE_FROM_FAVORITE';
